---
Name: theme-framework
After:
  - 'framework/*'
  - 'cms/*'
---
SiteConfig:
  extensions: 
    - ThemeSiteConfigExtension
Controller:
  extensions:
    - ThemePageControllerExtension
ThemePageControllerExtension:
  include_jquery: true
  include_jquery_ui: false
  # if none is set, default smoothness will be used
  jquery_ui_theme: null